import type { Metadata } from "next";
import { Inter, Reenie_Beanie, Francois_One } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const reenie_beanie = Reenie_Beanie({ subsets: ["latin"], variable: "--font-reenie-beanie", weight: "400"})
const francois_one = Francois_One({weight: "400", subsets: ["latin"], variable: "--font-francois-one"})
export const metadata: Metadata = {
  title: "useState practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${reenie_beanie.variable} ${francois_one.variable}`}>{children}</body>
    </html>
  );
}
